<?php
/**
 * Created by PhpStorm.
 * User: ZZHPENG
 * QQ: 398949389
 * Date: 2018/4/13/013
 * Time: 9:38
 */

namespace app\api\controller\v1;


use app\api\controller\BaseController;
use app\api\service\Match as MatchService;
use app\api\validate\IDMustBePositiveInt;
use app\api\model\Match as MatchModel;

class Match extends BaseController
{

    protected $id;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
//        $this->id = TokenService::getCurrentUId();
        $this->id = 1;
    }

    public function getWaitToMatchUsers(){
        $matchData = MatchService::getWaitToMatchData($this->id);
        return json($matchData,200);
    }

    public function leftSlide(){
        (new IDMustBePositiveInt())->goCheck();
        MatchService::DealWithThink($this->id,input('id'),input('level') );

    }

    public function rightSlide(){
        return 'todo';
    }
}