<?php
/**
 * Created by PhpStorm.
 * User: ZZHPENG
 * QQ: 398949389
 * Date: 2018/4/13/013
 * Time: 9:38
 */

namespace app\api\controller\v1;


use app\api\controller\BaseController;
use app\api\service\Match as MatchService;
use app\api\validate\IDMustBePositiveInt;
use app\api\model\Match as MatchModel;
use app\api\validate\SlideDataValidate;

class Match extends BaseController
{

    protected $id;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
//        $this->id = TokenService::getCurrentUId();
        $this->id = 1;
    }

    public function getWaitToMatchUsers(){
        $matchData = MatchService::getWaitToMatchData($this->id);
        return json($matchData,200);
    }

    public function slide(){
        (new SlideDataValidate())->goCheck();
        $slide_result =  MatchService::DealWithSlideData($this->id,input('object_id'),input('level') );
        return json($slide_result);
    }

}
