<?php
/**
 * Created by PhpStorm.
 * User: ZZHPENG
 * QQ: 398949389
 * Date: 2018/4/13/013
 * Time: 9:38
 */

namespace app\api\controller\v1;


use app\api\controller\BaseController;
use app\api\service\ComputeYear;
use app\api\service\Match as MatchService;
use app\api\validate\IDMustBePositiveInt;
use app\api\model\MatchInfo as MatchInfoModel;
use app\api\validate\SlideDataValidate;
use app\api\service\Token as TokenService;
use app\lib\exception\MatchException;

class Match extends BaseController
{

    protected $id;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->id = TokenService::getCurrentUId();
    }

    public function getWaitToMatchUsers(){
        $matchData = MatchService::getWaitToMatchData($this->id);
        return json($matchData,200);
    }

    public function slide(){
        (new SlideDataValidate())->goCheck();
        $slide_result =  MatchService::DealWithSlideData($this->id,input('object_id'),input('level') );
        return json($slide_result);
    }

    public function beSurperLike(){
        $super_result =  MatchInfoModel::beSuperLike($this->id);
        if($super_result->isEmpty()){
            throw new MatchException(
                [
                    'code'=>404,
                    'msg'=>'无超级喜欢你的人',
                    'errorCode'=>70003,
                ]
            );
        }
        return json($super_result);
    }

}
