<?php
/**
 * Created by PhpStorm.
 * User: ZZHPENG
 * QQ: 398949389
 * Date: 2018/4/10/010
 * Time: 16:25
 */

namespace app\api\controller\v1;


use app\api\controller\BaseController;
use app\api\model\ExtendSetting as ExtendSettingModel;
use app\api\model\Setting as SettingModel;
use app\api\service\Token as TokenService;
use app\api\validate\IDMustBePositiveInt;
use app\lib\exception\SettingMissException;

class Setting extends BaseController
{
    protected $id;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
//        $this->id = TokenService::getCurrentUId();
          $this->id = 1;
    }

    public function getSetting(){
        (new IDMustBePositiveInt())->goCheck();
        $setting = SettingModel::getSetting($this->id);
        if(!$setting){
            throw new SettingMissException();
        }
        return json($setting,200);
    }

    public function getExSetting(){
        (new IDMustBePositiveInt())->goCheck();
        $setting = ExtendSettingModel::getExSetting($this->id);
        if(!$setting){
            throw new SettingMissException();
        }
        return json($setting,200);
    }
}