<?php
/**
 * Created by PhpStorm.
 * User: ZZHPENG
 * QQ: 398949389
 * Date: 2018/4/10/010
 * Time: 13:06
 */

namespace app\api\controller\v1;


use app\api\controller\BaseController;
use app\api\model\User as UserModel;
use app\api\service\Token as TokenService;
use app\api\validate\IDMustBePositiveInt;
use app\api\validate\UserValidate;
use app\lib\exception\UserException;

class User extends BaseController
{

//    protected $beforeActionList =[
//        'needPrimaryScope'=>['only'=>'user_info']
//    ];
    protected $uid;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->uid = 1;
    }

    //获取用户信息
    public function getById(){
        (new IDMustBePositiveInt())->goCheck();
        $id =$this->uid;
        $UserInfo = UserModel::getUserInfo($id);
        if(!$UserInfo){
            throw new UserException();
        }
        return json($UserInfo,200);
    }

    //编辑个人基本信息
    public function updateUserBase(){
        (new UserValidate())->goCheck('base');
        $id = $this->uid;
        $user = new UserModel();
        $user->nickname = $_POST['nickname'];
        $user->birthday = $_POST['birthday'];
        $user->id = $id;
        $update_result=  $user->isUpdate()->save();
        if(!$update_result){
            throw new UserException([
                'msg'=>'用户信息更新失败',
                'errorCode'=>60003
            ]);
        }
        return json(['status'=>1],200);
    }
}